"""Add models stores and sopupons

Revision ID: 8c02c3e6b029
Revises: e951c0138e89
Create Date: 2022-09-23 05:47:27.586551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c02c3e6b029'
down_revision = 'e951c0138e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('procentage', sa.Float(precision=2), nullable=True),
    sa.Column('started_ad', sa.DateTime(), nullable=True),
    sa.Column('ended_ad', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    op.drop_table('coupons')
    # ### end Alembic commands ###
